A bunch of additions
ASEAN-Build-The-Earth/ASEAN-API-V2 pull request #16
Opened 2021-12-13 03:16 UTC by StoneMcYT

2021-12-13 03:19 UTC, Kira272921 requested changes
Use `tenor` links for gifs and `imgur` for images :shipit:

2021-12-13 03:26 UTC, Kira272921 commented on data/dog/dog.json
> +		"image": ""
:shipit: why is there is empty `value` ?

2021-12-13 03:32 UTC, Kira272921 requested changes
:octocat:

2021-12-15 06:56 UTC, StoneMcYT commented
Still a WiP

2021-12-15 06:59 UTC, Kira272921 reviewed
:trollface:

2021-12-15 06:59 UTC, Kira272921 commented on data/meme/meme.json
> +        "image": "https://i.imgur.com/Vlk1Gc4.mp4"
no MP4 pleaze ;-;

2021-12-15 06:59 UTC, Kira272921 commented on data/meme/meme.json
> +        "image": "https://i.imgur.com/1yFXNZw.mp4"
whyyyyyy ;-;

2021-12-15 06:59 UTC, Kira272921 commented on index.js
> +app.get('/api/v1/Dog', (req, res) => {
make the endpoint lowercase, coz lowercase is kul

2021-12-16 05:11 UTC, Kira272921 reviewed
@StoneMcYT import the JSON files into index.js as well when you create new endpoint

2021-12-16 05:11 UTC, Kira272921 commented on index.js
> +const dataDog = require('./data/dog/dog.json')
import the fox and bird JSON files as well

2021-12-16 07:48 UTC, merged